import { School } from './types'

export const schools: School[] = [
  { name: 'Arizona State University', id: 'asu' },
  { name: 'Baylor University', id: 'baylor' },
  { name: 'Belmont University', id: 'belmont' },
  { name: 'Boston College', id: 'bc' },
  { name: 'Brandeis University', id: 'brandeis' },
  { name: 'Brown University', id: 'brown' },
  { name: 'Cal Poly', id: 'calpoly' },
  { name: 'Cal State Fullerton', id: 'calstatefullerton' },
  { name: 'Clemson', id: 'clemson' },
  { name: 'CO School of Mines', id: 'mines' },
  { name: 'Columbia University', id: 'columbia' },
  { name: 'ETS Montreal', id: 'ets' },
  { name: 'FIU', id: 'fiu' },
  { name: 'Georgia College & State University', id: 'gcsu' },
  { name: 'Georgia Tech', id: 'gatech' },
  { name: 'Iowa State University', id: 'iowa-state' },
  { name: 'Louisiana State University', id: 'lsu' },
  { name: 'Loyola Marymount University', id: 'lmu' },
  { name: 'McGill University', id: 'mcgill' },
  { name: 'North Carolina State University', id: 'ncsu' },
  { name: 'Providence College', id: 'providence' },
  { name: 'Purdue University', id: 'purdue' },
  { name: 'San Antonio College', id: 'sanantonio' },
  { name: 'Smith College', id: 'smith' },
  { name: 'SUNY Brockport', id: 'sunybrockport' },
  { name: 'Texas State University', id: 'texasstate' },
  { name: 'UCLA', id: 'ucla' },
  { name: 'UC Irvine', id: 'irvine' },
  { name: 'UC Santa Barbara', id: 'ucsb' },
  { name: 'UC San Diego', id: 'ucsd' },
  { name: 'UC Santa Cruz', id: 'ucsc' },
  { name: 'University of Buffalo', id: 'buffalo' },
  { name: 'University of Calgary', id: 'ucalgary' },
  { name: 'University of Central Florida', id: 'ucf' },
  { name: 'University of Denver', id: 'denver' },
  { name: 'University of Hartford', id: 'hartford' },
  { name: 'University of Missouri', id: 'mizzou' },
  { name: 'University of Regina', id: 'regina' },
  { name: 'University of Rochester', id: 'rochester' },
  { name: 'University of South Carolina', id: 'carolina' },
  { name: 'University of Texas - Dallas', id: 'utdallas' },
  { name: 'University of Virginia', id: 'uva' },
  { name: 'University of Waterloo', id: 'waterloo' },
  { name: 'University of Wisconsin - Madison', id: 'uwmadison' },
  { name: 'uOttawa', id: 'ottawa' },
  { name: 'Wake Forest University', id: 'wake-forest' },
  { name: 'Westminster Schools', id: 'westminster' }
];

